//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyGroupDiary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostigenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostigenia()
        {
            this.Type = new HashSet<Type>();
        }
    
        public int DID { get; set; }
        public int DUID { get; set; }
        public string NameDosti { get; set; }
        public Nullable<int> Mesto { get; set; }
        public Nullable<int> TypeDosti { get; set; }
        public byte[] ImageDosti { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Type { get; set; }
    }
}
