//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyGroupDiary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EID { get; set; }
        public string YearOfEnrollment { get; set; }
        public string EndDate { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public bool SessionExtension { get; set; }
        public Nullable<int> ContractNumber { get; set; }
        public int UIDE { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
