//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyGroupDiary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalBusiness
    {
        public int UIDPB { get; set; }
        public int SNILS { get; set; }
        public int INN { get; set; }
        public string Specialization { get; set; }
        public bool APass { get; set; }
        public int CreditCardNumber { get; set; }
        public System.DateTime YearOfRecruitment { get; set; }
        public bool Benefits { get; set; }
        public bool BlockInTheStatement { get; set; }
        public bool Arrears { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
