//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyGroupDiary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyGroupDiaryBDEntities : DbContext
    {
        private static StudyGroupDiaryBDEntities _context;
        public StudyGroupDiaryBDEntities()
            : base("name=StudyGroupDiaryBDEntities")
        {
        }

        public static StudyGroupDiaryBDEntities GetContext()
        {
            if (_context == null)
                _context = new StudyGroupDiaryBDEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dostigenia> Dostigenia { get; set; }
        public virtual DbSet<Enrollment> Enrollment { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Passports> Passports { get; set; }
        public virtual DbSet<PersonalBusiness> PersonalBusiness { get; set; }
        public virtual DbSet<Spevialisition> Spevialisition { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
